version: "3.2"

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    restart: unless-stopped
    volumes:
       - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
    ports:
      - 5672:5672
      - 15672:15672
      - 1883:1883
    #command: "/bin/bash -c \"rabbitmq-plugins enable rabbitmq_mqtt\""
